=== navin-hariharan/FLUX-INFERENCE-LORA/schema.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "Model: Flux.1 Dev | Custom Lora",
      "author": "Black Forest Labs: Andreas Blattmann, Andrew Holmes, Axel Sauer, Dominik Lorenz, Dustin Podell, Frederic Boesel, Harry Saini, Jonas MÃ¼ller, Kyle Lacey, Patrick Esser, Robin Rombach, Sumith Kulal, Tim Dockhorn, Yam Levi, Zion English",
      "page": "https://blackforestlabs.ai/",
      "code": "https://github.com/black-forest-labs/flux",
      "jupyter": "https://github.com/camenduru/flux-jupyter",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/flux.1-dev-lora.ipynb",
      "tags": [
        "Text to Image"
      ],
      "widget": "readme"
    },
    "positive_prompt": {
      "type": "string",
      "description": "Prompt",
      "widget": "textarea"
    },
    "seed": {
      "type": "integer",
      "description": "Seed (if 0 random)"
    },
    "steps": {
      "type": "integer",
      "widget": "select",
      "description": "Steps",
      "oneOf": [
        {
          "description": "10",
          "enum": [
            10
          ]
        },
        {
          "description": "20",
          "enum": [
            20
          ]
        },
        {
          "description": "30",
          "enum": [
            30
          ]
        }
      ],
      "default": 20
    },
    "guidance": {
      "type": "number",
      "description": "Guidance"
    },
    "upload": {
      "type": "string",
      "widget": "upload",
      "upload_url": "https://litterbox.catbox.moe/resources/internals/api.php",
      "property": "lora_url"
    },
    "lora_url": {
      "type": "string",
      "description": "Lora URL",
      "widget": "textarea"
    },
    "lora_strength_model": {
      "type": "number",
      "widget": "select",
      "description": "Lora Strength Model",
      "oneOf": [
        {
          "description": "0",
          "enum": [
            0
          ]
        },
        {
          "description": "0.5",
          "enum": [
            0.5
          ]
        },
        {
          "description": "1",
          "enum": [
            1
          ]
        }
      ],
      "default": 1
    },
    "lora_strength_clip": {
      "type": "number",
      "widget": "select",
      "description": "Lora Strength Clip",
      "oneOf": [
        {
          "description": "0",
          "enum": [
            0
          ]
        },
        {
          "description": "0.5",
          "enum": [
            0.5
          ]
        },
        {
          "description": "1",
          "enum": [
            1
          ]
        }
      ],
      "default": 1
    },
    "sampler_name": {
      "type": "string",
      "widget": "select",
      "description": "Sampler Name",
      "oneOf": [
        {
          "description": "euler",
          "enum": [
            "euler"
          ]
        },
        {
          "description": "heun",
          "enum": [
            "heun"
          ]
        },
        {
          "description": "heunpp2",
          "enum": [
            "heunpp2"
          ]
        },
        {
          "description": "dpm_2",
          "enum": [
            "dpm_2"
          ]
        },
        {
          "description": "lms",
          "enum": [
            "lms"
          ]
        },
        {
          "description": "dpmpp_2m",
          "enum": [
            "dpmpp_2m"
          ]
        },
        {
          "description": "ipndm",
          "enum": [
            "ipndm"
          ]
        },
        {
          "description": "deis",
          "enum": [
            "deis"
          ]
        },
        {
          "description": "ddim",
          "enum": [
            "ddim"
          ]
        },
        {
          "description": "uni_pc",
          "enum": [
            "uni_pc"
          ]
        },
        {
          "description": "uni_pc_bh2",
          "enum": [
            "uni_pc_bh2"
          ]
        }
      ],
      "default": "euler"
    },
    "scheduler": {
      "type": "string",
      "widget": "select",
      "description": "Scheduler",
      "oneOf": [
        {
          "description": "normal",
          "enum": [
            "normal"
          ]
        },
        {
          "description": "sgm_uniform",
          "enum": [
            "sgm_uniform"
          ]
        },
        {
          "description": "simple",
          "enum": [
            "simple"
          ]
        },
        {
          "description": "ddim_uniform",
          "enum": [
            "ddim_uniform"
          ]
        }
      ],
      "default": "simple"
    },
    "width": {
      "type": "integer",
      "description": "Width"
    },
    "height": {
      "type": "integer",
      "description": "Height"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== navin-hariharan/FLUX-INFERENCE-LORA/model.json
{
    "positive_prompt": "A cat holding a sign that says 'I LOVE TOST!'",
    "seed": 0,
    "steps": 20,
    "guidance": 3.5,
    "lora_url": "https://huggingface.co/TostAI/flux-1-dev-lora/resolve/main/8iiu0y.safetensors",
    "lora_strength_model": 1,
    "lora_strength_clip": 1,
    "sampler_name": "euler",
    "scheduler": "simple",
    "width": 1024,
    "height": 1024
}
